//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 数据库设计练习
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public string studentID { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public string major { get; set; }
        public string roomID { get; set; }
    }
}
